// ─── Port data ───────────────────────────────────────────────────────────────
// `icon`    — Devicons class name (devicon-*). Only set where the icon is
//             confirmed to exist in devicon. Omit if no devicon icon available.
// `emoji`   — Emoji fallback. Always required. Shown if devicon glyph fails to
//             render (e.g. icon not yet in devicon), or if no `icon` is set.
// `gh`      — 'owner/repo' for GitHub-hosted ports; drives the shields.io badge.
//             Omit for ports hosted elsewhere (addon stores, sr.ht, gists, etc.).
// `url`     — link target for the card.
// Ports with competing implementations use `variants` instead of a single entry.
//
// Categories: editors | terminals | browsers | websites | apps | desktop | other

const PORTS = [
  // ── Code Editors ──────────────────────────────────────────────────────────
  {
    category: "editors",
    name: "Doom Emacs",
    icon: "devicon-emacs-original",
    emoji: "📝",
    maintainer: "Cardoso1994",
    gh: "Cardoso1994/doom-everforest-theme",
    url: "https://github.com/Cardoso1994/doom-everforest-theme",
  },
  {
    category: "editors",
    name: "Emacs",
    icon: "devicon-emacs-original",
    emoji: "📝",
    maintainer: "theorytoe",
    url: "https://git.sr.ht/~theorytoe/everforest-theme",
  },
  {
    category: "editors",
    name: "Helix",
    emoji: "🧬",
    maintainer: "CptPotato",
    gh: "CptPotato/helix-themes",
    url: "https://github.com/CptPotato/helix-themes/tree/main/palettes/everforest",
  },
  {
    category: "editors",
    name: "Kakoune",
    emoji: "📝",
    maintainer: "jdugan6240",
    url: "https://codeberg.org/jdugan6240/everforest.kak",
  },
  {
    category: "editors",
    name: "Micro",
    emoji: "📝",
    maintainer: "atomashevic",
    gh: "atomashevic/everforest-micro",
    url: "https://github.com/atomashevic/everforest-micro",
  },
  {
    category: "editors",
    name: "Neovim",
    icon: "devicon-neovim-plain",
    emoji: "🟢",
    variants: [
      {
        maintainer: "sainnhe",
        gh: "sainnhe/everforest",
        url: "https://github.com/sainnhe/everforest",
      },
      {
        maintainer: "neanias",
        gh: "neanias/everforest-nvim",
        url: "https://github.com/neanias/everforest-nvim",
      },
    ],
  },
  {
    category: "editors",
    name: "Replit",
    emoji: "🔁",
    maintainer: "talwat321",
    url: "https://replit.com/theme/@talwat321/everforest",
  },
  {
    category: "editors",
    name: "TextMate / Sublime Text",
    icon: "devicon-sublimetext-plain",
    emoji: "✏️",
    variants: [
      {
        maintainer: "mhanberg",
        gh: "mhanberg/everforest-textmate",
        url: "https://github.com/mhanberg/everforest-textmate",
      },
      {
        maintainer: "avelican",
        gh: "avelican/everforest-sublime",
        url: "https://github.com/avelican/everforest-sublime",
      },
    ],
  },
  {
    category: "editors",
    name: "Vim",
    icon: "devicon-vim-plain",
    emoji: "🟢",
    maintainer: "sainnhe",
    gh: "sainnhe/everforest",
    url: "https://github.com/sainnhe/everforest",
  },
  {
    category: "editors",
    name: "VS Code",
    icon: "devicon-vscode-plain",
    emoji: "📘",
    maintainer: "sainnhe",
    gh: "sainnhe/everforest-vscode",
    url: "https://github.com/sainnhe/everforest-vscode",
  },
  {
    category: "editors",
    name: "Zed",
    emoji: "⚡",
    maintainer: "ThomasAlban",
    gh: "ThomasAlban/everforest-zed",
    url: "https://github.com/ThomasAlban/everforest-zed",
  },

  // ── IDEs (folded into Editors) ────────────────────────────────────────────
  {
    category: "editors",
    name: "Gnome Builder",
    emoji: "🛠️",
    maintainer: "ghostcrafter551",
    gh: "ghostcrafter551/everforest-gnome-builder",
    url: "https://github.com/ghostcrafter551/everforest-gnome-builder",
  },
  {
    category: "editors",
    name: "JetBrains IDEs",
    icon: "devicon-jetbrains-plain",
    emoji: "🛠️",
    maintainer: "francma",
    gh: "francma/everforest-jetbrains",
    url: "https://github.com/francma/everforest-jetbrains",
  },
  {
    category: "editors",
    name: "Visual Studio 2022",
    icon: "devicon-visualstudio-plain",
    emoji: "🟣",
    maintainer: "ZachFranzen",
    gh: "ZachFranzen/Everforest",
    url: "https://github.com/ZachFranzen/Everforest",
  },

  // ── Terminals ─────────────────────────────────────────────────────────────
  // Includes terminal emulators and CLI tooling
  {
    category: "terminals",
    name: "Alacritty",
    emoji: "🖥️",
    variants: [
      { maintainer: "sainnhe", url: "https://github.com/sainnhe/dotfiles" },
      {
        maintainer: "Official",
        gh: "alacritty/alacritty-theme",
        url: "https://github.com/alacritty/alacritty-theme",
      },
    ],
  },
  {
    category: "terminals",
    name: "colorls",
    icon: "devicon-ruby-plain",
    emoji: "💎",
    maintainer: "talwat",
    url: "https://github.com/talwat/dotfiles",
  },
  {
    category: "terminals",
    name: "Foot",
    emoji: "🖥️",
    maintainer: "jakesco",
    url: "https://gist.github.com/jakesco/c9b11f362f4ae0251ba2ca99a4e1e005",
  },
  {
    category: "terminals",
    name: "Ghostty",
    emoji: "🖥️",
    variants: [
      { maintainer: "Built-in", url: "https://ghostty.org/" },
      {
        maintainer: "metalelf0",
        gh: "metalelf0/everforest.ghostty",
        url: "https://github.com/metalelf0/everforest.ghostty",
      },
      {
        maintainer: "jrswab",
        gh: "jrswab/ghostty-everforest",
        url: "https://github.com/jrswab/ghostty-everforest",
      },
    ],
  },
  {
    category: "terminals",
    name: "Gnome Terminal",
    emoji: "🖥️",
    maintainer: "em3n",
    gh: "em3n/Everforest-GnomeTerminal",
    url: "https://github.com/em3n/Everforest-GnomeTerminal",
  },
  {
    category: "terminals",
    name: "Hyper",
    emoji: "⚡",
    maintainer: "tani",
    gh: "tani/hyper-everforest",
    url: "https://github.com/tani/hyper-everforest",
  },
  {
    category: "terminals",
    name: "iTerm2",
    icon: "devicon-apple-original",
    emoji: "🍎",
    variants: [
      {
        maintainer: "icewind",
        gh: "icewind/everforest.iterm2",
        url: "https://github.com/icewind/everforest.iterm2",
      },
      {
        maintainer: "sainnhe",
        url: "https://github.com/sainnhe/dotfiles/tree/master/.macos/iTerm2/colors",
      },
    ],
  },
  {
    category: "terminals",
    name: "Kitty",
    emoji: "🐱",
    maintainer: "Official",
    gh: "kovidgoyal/kitty-themes",
    url: "https://github.com/kovidgoyal/kitty-themes",
  },
  {
    category: "terminals",
    name: "Konsole",
    icon: "devicon-linux-plain",
    emoji: "🐧",
    maintainer: "sainnhe",
    url: "https://store.kde.org/c/1638326",
  },
  {
    category: "terminals",
    name: "MobaXterm",
    emoji: "🖥️",
    maintainer: "broot5",
    url: "https://gist.github.com/broot5/1d9d5ea97ef6e7cf48a31bd45e47e771",
  },
  {
    category: "terminals",
    name: "Tilix",
    emoji: "🖥️",
    maintainer: "spacefall",
    gh: "spacefall/everforest-tilix",
    url: "https://github.com/spacefall/everforest-tilix",
  },
  {
    category: "terminals",
    name: "tmux",
    icon: "devicon-bash-plain",
    emoji: "⬛",
    variants: [
      {
        maintainer: "TanglingTreats",
        gh: "TanglingTreats/tmux-everforest",
        url: "https://github.com/TanglingTreats/tmux-everforest",
      },
      {
        maintainer: "talwat",
        url: "https://github.com/talwat/dotfiles/blob/main/macOS/everforest/.tmux.conf",
      },
    ],
  },
  {
    category: "terminals",
    name: "Warp",
    emoji: "🖥️",
    maintainer: "Official",
    url: "https://docs.warp.dev/terminal/appearance/themes",
  },
  {
    category: "terminals",
    name: "WezTerm",
    emoji: "🖥️",
    maintainer: "frdwin",
    gh: "frdwin/everforest-for-wezterm",
    url: "https://github.com/frdwin/everforest-for-wezterm",
  },
  {
    category: "terminals",
    name: "Windows Terminal",
    icon: "devicon-windows8-original",
    emoji: "🪟",
    maintainer: "suppayami",
    url: "https://gist.github.com/suppayami/7d427d116b97564d1c565a7aed092d08",
  },
  {
    category: "terminals",
    name: "Xfce4-Terminal",
    icon: "devicon-linux-plain",
    emoji: "🐧",
    maintainer: "toabr",
    gh: "toabr/everforest-xfce4-terminal",
    url: "https://github.com/toabr/everforest-xfce4-terminal",
  },
  {
    category: "terminals",
    name: "Xresources",
    icon: "devicon-xorg-plain",
    emoji: "🖥️",
    maintainer: "jef",
    gh: "jef/everforest-xresources",
    url: "https://github.com/jef/everforest-xresources",
  },
  {
    category: "terminals",
    name: "Zellij",
    icon: "devicon-bash-plain",
    emoji: "⬛",
    maintainer: "ghostcrafter551",
    gh: "ghostcrafter551/everforest-dark-zellij",
    url: "https://github.com/ghostcrafter551/everforest-dark-zellij",
  },
  {
    category: "terminals",
    name: "Zsh",
    icon: "devicon-bash-plain",
    emoji: "⬛",
    maintainer: "sainnhe",
    url: "https://github.com/sainnhe/dotfiles/tree/master/.zsh-theme",
  },

  // ── Web Browsers ──────────────────────────────────────────────────────────
  {
    category: "browsers",
    name: "Chrome",
    icon: "devicon-chrome-plain",
    emoji: "🌐",
    maintainer: "talwat",
    url: "https://github.com/talwat/dotfiles/tree/main/macOS/everforest/chrome/everforest",
  },
  {
    category: "browsers",
    name: "Firefox",
    icon: "devicon-firefox-plain",
    emoji: "🦊",
    variants: [
      {
        maintainer: "sainnhe",
        url: "https://addons.mozilla.org/en-US/firefox/addon/everforest-dark-official/",
      },
      {
        maintainer: "talwat",
        url: "https://addons.mozilla.org/en-US/firefox/addon/everforest-medium-dark/",
      },
      {
        maintainer: "aaheen",
        url: "https://addons.mozilla.org/en-US/firefox/addon/everforest-spectrum-dark-soft",
      },
    ],
  },

  // ── Website Themes ────────────────────────────────────────────────────────
  {
    category: "websites",
    name: "Element",
    emoji: "💬",
    maintainer: "maksim",
    url: "https://git.sr.ht/~maksim/element-everforest",
  },
  {
    category: "websites",
    name: "Monkeytype",
    emoji: "⌨️",
    maintainer: "mel4tonin",
    url: "https://monkeytype.com/",
  },
  {
    category: "websites",
    name: "Nitter",
    icon: "devicon-twitter-original",
    emoji: "🐦",
    maintainer: "cozy-isaac",
    gh: "cozy-isaac/nitter-everforest",
    url: "https://github.com/cozy-isaac/nitter-everforest",
  },
  {
    category: "websites",
    name: "Proton (Mail, Calendar, Drive)",
    emoji: "🔒",
    maintainer: "cozy-isaac",
    gh: "cozy-isaac/proton-everforest",
    url: "https://github.com/cozy-isaac/proton-everforest",
  },
  {
    category: "websites",
    name: "Redlib / Libreddit",
    icon: "devicon-reddit-plain",
    emoji: "🤖",
    maintainer: "cozy-isaac",
    gh: "cozy-isaac/redlib-everforest",
    url: "https://github.com/cozy-isaac/redlib-everforest",
  },
  {
    category: "websites",
    name: "SearXNG",
    emoji: "🔍",
    maintainer: "cozy-isaac",
    gh: "cozy-isaac/searxng-everforest",
    url: "https://github.com/cozy-isaac/searxng-everforest",
  },
  {
    category: "websites",
    name: "YouTube",
    icon: "devicon-youtube-plain",
    emoji: "▶️",
    maintainer: "mel4tonin",
    gh: "mel4tonin/everforest-youtube",
    url: "https://github.com/mel4tonin/everforest-youtube",
  },

  // ── Applications ──────────────────────────────────────────────────────────
  {
    category: "apps",
    name: "Alfred",
    emoji: "🔍",
    maintainer: "mhanberg",
    gh: "mhanberg/everforest-alfred",
    url: "https://github.com/mhanberg/everforest-alfred",
  },
  {
    category: "apps",
    name: "Calibre",
    emoji: "📚",
    maintainer: "morph626",
    url: "https://gist.github.com/morph626/76dbe01a7e245ca6e6d67c5ca76bf953",
  },
  {
    category: "apps",
    name: "ComfyUI",
    emoji: "🎨",
    maintainer: "ilonis",
    gh: "Ilonis/everforest-ComfyUI",
    url: "https://github.com/Ilonis/everforest-ComfyUI",
  },
  {
    category: "apps",
    name: "Insomnia",
    emoji: "🌙",
    maintainer: "talwat",
    gh: "talwat/insomnia-plugin-everforest-theme",
    url: "https://github.com/talwat/insomnia-plugin-everforest-theme",
  },
  {
    category: "apps",
    name: "Logseq",
    emoji: "📓",
    maintainer: "khoulihan",
    gh: "khoulihan/logseq-everforest-theme",
    url: "https://github.com/khoulihan/logseq-everforest-theme",
  },
  {
    category: "apps",
    name: "Obsidian",
    emoji: "🔮",
    variants: [
      {
        maintainer: "kepano",
        gh: "kepano/obsidian-minimal",
        url: "https://github.com/kepano/obsidian-minimal",
      },
      {
        maintainer: "0xGlitchByte",
        gh: "0xGlitchByte/obsidian_everforest",
        url: "https://github.com/0xGlitchbyte/obsidian_everforest",
      },
      {
        maintainer: "FireIsGood",
        gh: "FireIsGood/obsidian-everforest-enchanted",
        url: "https://github.com/FireIsGood/obsidian-everforest-enchanted",
      },
    ],
  },
  {
    category: "apps",
    name: "Slack",
    icon: "devicon-slack-plain",
    emoji: "💬",
    maintainer: "itendtostare",
    gh: "itendtostare/everforest-slack",
    url: "https://github.com/itendtostare/everforest-slack",
  },
  {
    category: "apps",
    name: "Telegram",
    icon: "devicon-telegram-plain",
    emoji: "✈️",
    maintainer: "Skartorion",
    gh: "Skartorion/telegram-everforest",
    url: "https://github.com/Skartorion/telegram-everforest",
  },
  {
    category: "apps",
    name: "Typora",
    emoji: "📝",
    maintainer: "YuxBao",
    gh: "YuxBao/everforest-typora",
    url: "https://github.com/YuxBao/everforest-typora",
  },
  {
    category: "apps",
    name: "Zathura",
    emoji: "📄",
    maintainer: "maksim",
    url: "https://git.sr.ht/~maksim/zathura-everforest",
  },

  // ── Desktop ───────────────────────────────────────────────────────────────
  {
    category: "desktop",
    name: "Cursors",
    emoji: "🖱️",
    maintainer: "talwat",
    gh: "talwat/everforest-cursors",
    url: "https://github.com/talwat/everforest-cursors",
  },
  {
    category: "desktop",
    name: "GTK",
    icon: "devicon-gnome-plain",
    emoji: "🐾",
    maintainer: "Fausto-Korpsvart",
    gh: "Fausto-Korpsvart/Everforest-GTK-Theme",
    url: "https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme",
  },
  {
    category: "desktop",
    name: "i3 / i3-gaps",
    icon: "devicon-linux-plain",
    emoji: "🐧",
    maintainer: "3rfaan",
    url: "https://github.com/3rfaan/dotfiles",
  },
  {
    category: "desktop",
    name: "KDE",
    icon: "devicon-linux-plain",
    emoji: "🐧",
    maintainer: "Serge2702",
    gh: "Serge2702/KDE-Everforest",
    url: "https://github.com/Serge2702/KDE-Everforest",
  },
  {
    category: "desktop",
    name: "Libadwaita (Gradience)",
    icon: "devicon-gnome-plain",
    emoji: "🐾",
    maintainer: "ghostcrafter551",
    url: "https://raw.githubusercontent.com/GradienceTeam/Community/next/curated/everforest.json",
  },
  {
    category: "desktop",
    name: "Polybar",
    icon: "devicon-linux-plain",
    emoji: "🐧",
    maintainer: "3rfaan",
    url: "https://github.com/3rfaan/dotfiles",
  },

  // ── Other ─────────────────────────────────────────────────────────────────
  {
    category: "other",
    name: "dipc",
    icon: "devicon-rust-plain",
    emoji: "🦀",
    maintainer: "doprz",
    gh: "doprz/dipc",
    url: "https://github.com/doprz/dipc/",
  },
  {
    category: "other",
    name: "Gitea",
    icon: "devicon-gitea-plain",
    emoji: "🍵",
    maintainer: "sainnhe",
    url: "https://git.sainnhe.dev/sainnhe/gitea-themes",
  },
  {
    category: "other",
    name: "NixOS",
    icon: "devicon-nixos-plain",
    emoji: "❄️",
    maintainer: "fwinter",
    url: "https://codeberg.org/fwinter/everforest-nix",
  },
  {
    category: "other",
    name: "Shiki.js",
    icon: "devicon-javascript-plain",
    emoji: "✨",
    maintainer: "serdonke",
    url: "https://shiki.style/",
  },
];

// ─── Sort alphabetically within each category ─────────────────────────────────
PORTS.sort((a, b) => a.name.localeCompare(b.name));
